rm(list=ls())
setwd("C:/Users/Douglas/Dropbox (ASU)/Research/Landscape Ecology Research/Data/Plant Sampling")
ASU_Douglas.Lawton_Pont.incercept2016<-read.csv("ASU_Douglas Lawton_Pont incercept2016.csv")
T1<-subset(ASU_Douglas.Lawton_Pont.incercept2016, ASU_Douglas.Lawton_Pont.incercept2016$Transect==1)
T2<-subset(ASU_Douglas.Lawton_Pont.incercept2016, ASU_Douglas.Lawton_Pont.incercept2016$Transect==2)
T3<-subset(ASU_Douglas.Lawton_Pont.incercept2016, ASU_Douglas.Lawton_Pont.incercept2016$Transect==3)
T4<-subset(ASU_Douglas.Lawton_Pont.incercept2016, ASU_Douglas.Lawton_Pont.incercept2016$Transect==4)
T5<-subset(ASU_Douglas.Lawton_Pont.incercept2016, ASU_Douglas.Lawton_Pont.incercept2016$Transect==5)
T6<-subset(ASU_Douglas.Lawton_Pont.incercept2016, ASU_Douglas.Lawton_Pont.incercept2016$Transect==6)
T7<-subset(ASU_Douglas.Lawton_Pont.incercept2016, ASU_Douglas.Lawton_Pont.incercept2016$Transect==7)
T8<-subset(ASU_Douglas.Lawton_Pont.incercept2016, ASU_Douglas.Lawton_Pont.incercept2016$Transect==8)
T9<-subset(ASU_Douglas.Lawton_Pont.incercept2016, ASU_Douglas.Lawton_Pont.incercept2016$Transect==9)
T10<-subset(ASU_Douglas.Lawton_Pont.incercept2016, ASU_Douglas.Lawton_Pont.incercept2016$Transect==10)
T11<-subset(ASU_Douglas.Lawton_Pont.incercept2016, ASU_Douglas.Lawton_Pont.incercept2016$Transect==11)
T12<-subset(ASU_Douglas.Lawton_Pont.incercept2016, ASU_Douglas.Lawton_Pont.incercept2016$Transect==12)
T1.s1<-as.data.frame(table(T1$Species.1))
T1.s2<-as.data.frame(table(T1$Species.2))
T1.s3<-as.data.frame(table(T1$Species.3))

T2.s2<-as.data.frame(table(T2$Species.2))
T2.s1<-as.data.frame(table(T2$Species.1))
T2.s3<-as.data.frame(table(T2$Species.3))

T3.s2<-as.data.frame(table(T2$Species.2))
T3.s1<-as.data.frame(table(T1$Species.1))
T3.s3<-as.data.frame(table(T2$Species.3))

T4.s2<-as.data.frame(table(T4$Species.2))
T4.s1<-as.data.frame(table(T4$Species.1))
T4.s3<-as.data.frame(table(T4$Species.3))

T5.s2<-as.data.frame(table(T5$Species.2))
T5.s1<-as.data.frame(table(T5$Species.1))
T5.s3<-as.data.frame(table(T5$Species.3))

T6.s2<-as.data.frame(table(T6$Species.2))
T6.s1<-as.data.frame(table(T6$Species.1))
T6.s3<-as.data.frame(table(T6$Species.3))

T7.s2<-as.data.frame(table(T7$Species.2))
T7.s1<-as.data.frame(table(T7$Species.1))
T7.s3<-as.data.frame(table(T7$Species.3))

T8.s2<-as.data.frame(table(T8$Species.2))
T8.s1<-as.data.frame(table(T8$Species.1))
T8.s3<-as.data.frame(table(T8$Species.3))

T9.s2<-as.data.frame(table(T9$Species.2))
T9.s1<-as.data.frame(table(T9$Species.1))
T9.s3<-as.data.frame(table(T9$Species.3))

T10.s1<-as.data.frame(table(T10$Species.1))
T10.s2<-as.data.frame(table(T10$Species.2))
T10.s3<-as.data.frame(table(T10$Species.3))

T11.s1<-as.data.frame(table(T11$Species.1))
T11.s2<-as.data.frame(table(T11$Species.2))
T11.s3<-as.data.frame(table(T11$Species.3))

T12.s1<-as.data.frame(table(T12$Species.1))
T12.s2<-as.data.frame(table(T12$Species.2))
T12.s3<-as.data.frame(table(T12$Species.3))
SxT<-read.csv("SpeciesxTransect.csv")
Grass.SxT<-subset(SxT,SxT$Type=="Grass")
sum(SxT$X1, na.rm=TRUE)
sum(SxT$X2, na.rm=TRUE)
sum(SxT$X3, na.rm=TRUE)
sum(SxT$X4, na.rm=TRUE)
sum(SxT$X5, na.rm=TRUE)
sum(SxT$X6, na.rm=TRUE)
sum(SxT$X7, na.rm=TRUE)
sum(SxT$X8, na.rm=TRUE)
sum(SxT$X9, na.rm=TRUE)
sum(SxT$X10, na.rm=TRUE)
sum(SxT$X11, na.rm=TRUE)
sum(SxT$X12, na.rm=TRUE)

